// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=ts"
// @generated from file echo.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EchoRequest, EchoResponse } from "./echo_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service EchoService
 */
export const EchoService = {
  typeName: "EchoService",
  methods: {
    /**
     * @generated from rpc EchoService.Echo
     */
    echo: {
      name: "Echo",
      I: EchoRequest,
      O: EchoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

